### ISSUE TITLE
Schwarzes Brett mit Twitter

### ISSUE THREAD

**Issue by DracoBlue** [University-of-Potsdam-MM/rooms#14]
* Gesucht nach Hash-Tag

**Comment by alekiy** [comment]
Ähnlich zu den Vorstellungen zum schwarzen Brett würden wir "einfach" einige Tweets mehrerer konfigurierbarer Ersteller in einer Liste darstellen. Optimal wäre wenn dies auch für Campus konfigurierbar wäre. So kommen für Griebnitzsee bspw. folgende in Betracht:
- https://twitter.com/unipotsdam
- https://twitter.com/astaup
- https://twitter.com/fsr_wiwi_up

**Comment by alekiy** [comment]
Erst einmal geschlossen. Konfiguration erfolgt über Twitter-Widgets.
