### ISSUE TITLE
Kasten mit aktuellen ÖPNV-Verbindungen bei der Veranstaltungsansicht

### ISSUE THREAD

**Issue by DracoBlue** [University-of-Potsdam-MM/rooms#17]
Eventuell oben rechts.

**Comment by DracoBlue** [comment]
Das hab ich jetzt mal so ausprobiert:

<img width="590" alt="bildschirmfoto 2015-07-12 um 23 24 43" src="https://cloud.githubusercontent.com/assets/35926/8640116/4d383192-28ed-11e5-9ccb-a26af0fd44e6.png">

**Comment by alekiy** [comment]
Es geht ein wenig unter mit ein wenig CSS bekommt man das aber hin.

**Comment by DracoBlue** [comment]
Hab das mal etwas nach unten verschoben:

<img width="609" alt="bildschirmfoto 2015-08-01 um 14 36 52" src="https://cloud.githubusercontent.com/assets/35926/9021857/d9563bb6-385a-11e5-9970-87df7d0185d3.png">

Ist im 1.1-dev Branch jetzt enthalten und CSSig stylebar.

**Comment by alekiy** [comment]
Passt. Wir stylen und schauen wie es ankommt.
