### ISSUE TITLE
Neuigkeiten (Pressemitteilungsscreen) (E3 Variante und zusätzlich zum Testen mit Bild 100% unter Überschrift)

### ISSUE THREAD

**Issue by DracoBlue** [University-of-Potsdam-MM/rooms#18]
![e](https://cloud.githubusercontent.com/assets/35926/7021890/90c9165a-dd26-11e4-8da7-fa35b7443b42.jpg)

http://www.uni-potsdam.de/presse/nachrichten-veranstaltungen/nachrichten.html

**Comment by DracoBlue** [comment]
Ist nun in #25 bearbeitet.

**Comment by DracoBlue** [comment]
2 auf der Nachrichtenseite:
<img width="575" alt="bildschirmfoto 2015-07-12 um 16 18 50" src="https://cloud.githubusercontent.com/assets/35926/8639620/010edefe-28e0-11e5-8cd2-e58765f2d44b.png">

3 auf der Nachrichtenseite:
<img width="575" alt="bildschirmfoto 2015-07-12 um 16 18 08" src="https://cloud.githubusercontent.com/assets/35926/8639621/011014b8-28e0-11e5-8af4-8344be64b169.png">

**Comment by alekiy** [comment]
Sieht bereits ganz gut aus. Wenn du die Bilder noch ein wenig stylst und eine Border oder Shadow vergibst heben sich die voneinander und von den freien Räumen besser ab.
Von der Proportion her finde ich zwei Bilder bisher besser, das könnte man sich aber auf dem Panel noch ansehen.
