### ISSUE TITLE
Anzeige von Anzeigen / Veranstaltungen als Gesamtseite

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/rooms#25]

**Comment by DracoBlue** [comment]
Ansicht mit 2 News pro Seite:

<img width="575" alt="bildschirmfoto 2015-07-12 um 16 18 08" src="https://cloud.githubusercontent.com/assets/35926/8638152/a6976b22-28b1-11e5-8f49-d6b4c2c173b0.png">

Mit 2 News pro Seite:

<img width="575" alt="bildschirmfoto 2015-07-12 um 16 18 50" src="https://cloud.githubusercontent.com/assets/35926/8638154/c83de260-28b1-11e5-8570-673bea9dad00.png">

**Comment by DracoBlue** [comment]
Oh, es geht hier ja um Veranstaltungen und nicht um Nachrichten. Wieder geöffnet die #18

**Comment by DracoBlue** [comment]
Ein Beispiel (mit Datum + Zeit):

<img width="590" alt="bildschirmfoto 2015-07-12 um 22 30 37" src="https://cloud.githubusercontent.com/assets/35926/8639848/a8f877a6-28e5-11e5-9d41-72a54c9dbf97.png">

Im Rss hab ich aktuell leider nur das Startdatum. Daher würde ich dort nur die Veranstaltungen anzeigen, die noch nicht begonnen haben und in der Zukunft liegen.

**Comment by DracoBlue** [comment]
Ich habe noch eingebaut, dass man sieht an welchem Campus die Veranstaltung ist.

<img width="590" alt="bildschirmfoto 2015-07-12 um 22 52 05" src="https://cloud.githubusercontent.com/assets/35926/8639991/a9e452a4-28e8-11e5-84c9-f0dd0852e381.png">

**Comment by DracoBlue** [comment]
Oder ist mit "Anzeigen" sowas wie Werbung gemeint? @alekiy

**Comment by alekiy** [comment]
Genau eher sowas wie Werbung. D.h. die Leute haben eine HTML-Seite oder einen DIV-Container um sich auszutoben und der Inhalt wird als eigenständige Ansicht/Seite auf dem Panel dargestellt. So wollte bspw. UniContact Werbung für http://www.unicontact-potsdam.de/ schalten was nur Haus 6 spezifisch wäre, da dort das Event stattfindet.

**Comment by alekiy** [comment]
Von der Funktionalität her sind die Veranstaltungen beinahe mit Nachrichten gleichzusetzen. Ich kläre bis Freitag ob wir das ggf. für den vorlesungsfreien Zeitraum auch mit anbieten möchten.
