### ISSUE TITLE
Rss-Feed BilderURL ist fehlerhaft

### ISSUE THREAD

**Issue by DracoBlue** [University-of-Potsdam-MM/rooms#26]
Das unter http://www.uni-potsdam.de/presse/nachrichten-veranstaltungen/nachrichten/rss-feed-abonnieren.html?type=100&tx_ttnews%5Bcat%5D=19 verfügbar rss-feed gibt zwar Bild-URLs mit aus, leider jedoch alles 404er.

Ausgegeben wird z.B.:

http://www.uni-potsdam.de/uploads/pics/FidH_Unterzeichnung_Charta_150615_2_orig.jpg

korrekt wäre aber:

http://www.uni-potsdam.de/uploads01/pics/FidH_Unterzeichnung_Charta_150615_2_orig.jpg

(siehe uploads vs uploads01)

@alekiy

**Comment by alekiy** [comment]
Ist bekannt und wird kommende Woche vom Dienstleister bearbeitet.

**Comment by alekiy** [comment]
Sollte behoben sein. Bitte prüfen @DracoBlue

**Comment by DracoBlue** [comment]
Sieht gut aus
