### ISSUE TITLE
ÖPNV Infos nur für in 1 Minute + x

### ISSUE THREAD

**Issue by DracoBlue** [University-of-Potsdam-MM/rooms#29]
... derzeit steht manchmal "vor wenigen Sekunden" da.

**Comment by alekiy** [comment]
@DracoBlue Ist hier noch was zu machen?

**Comment by DracoBlue** [comment]
Nope, nur der 1.1-dev Branch muss in master zurückgeführt werden. Dann schließt github das Ticket automatisch.
