### ISSUE TITLE
CSS-Anpassung

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/rooms#3]
Wie besprochen erfolgt bei einer Zoomstufe vom 175%? ein "unschöner" Umbruch im CSS. ggf. den Titel auspunkten oder den Namen (bspw. C.A.) entfernen.

**Comment by alekiy** [comment]
CSS-Anpassungen nehmen wir vor. @Clickmari bitte melden sobald du wieder ansprechbar bist. Wir gehen dann die Struktur grob zusammen durch.

**Comment by alekiy** [comment]
Grobe CSS-Anpassungen vorgenommen. Bitte noch folgende Punkte anpassen:
- [ ] Nahverkehrsübersicht: Icons für Verkehrsmittel hinzufügen

Das Styling von Veranstaltungen / Neuigkeiten wird in einem anderen Ticket #33 behandelt. Hier muss @Clickmari zunächst nichts machen.

**Comment by Clickmari** [comment]
kann denn da mal jemand eine klass hinlegen, die mir sagt ob das ein bus ist, eine bahn oder eine sbahn?

**Comment by alekiy** [comment]
@Clickmari gibt nun die Klassen:
- Bus
- S
- RB

**Comment by alekiy** [comment]
Passt. Danke.
