### ISSUE TITLE
Page-Container für Werbung

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/rooms#30]
Siehe #25 bspw. sofern UniContact Werbung für http://www.unicontact-potsdam.de/ schalten möchte und das Event speziell in einem Haus statt findet.

**Comment by alekiy** [comment]
AJAX-Call mit lokalen HTML-Sniplets

**Comment by DracoBlue** [comment]
Ist im Branch eingefügt und in der README.md dokumentiert.

**Comment by alekiy** [comment]
Ist ausreichend für meine Zwecke.
