### ISSUE TITLE
Syntax Error für Veranstaltungen und Neuigkeiten

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/rooms#31]
URL: http://streifenroller.cs.uni-potsdam.de/rooms

```
/rooms/static/bower_components/jquery/jquery.js?cb=1439214645741:1850 Uncaught Error: Syntax error, unrecognized expression: <?php

header('Content-Type: application/xml');
echo file_get_contents('http://www.uni-potsdam.de/nachrichten/rss-feed-abonnieren.html?type=100&tx_ttnews%5Bcat%5D=19');
/rooms/static/bower_components/jquery/jquery.js?cb=1439214645741:1850 Uncaught Error: Syntax error, unrecognized expression: <?php

header('Content-Type: application/xml');
echo file_get_contents('https://www.uni-potsdam.de/veranstaltungen/rss-feed-abonnieren/eventfeed/fe…&tx_upevents_upeventfeed%5Bcat%5D=&tx_upevents_upeventfeed%5BcatLink%5D=or');
```

**Comment by DracoBlue** [comment]
Wäre gut, wenn da php ausgegührt wird ;).

Am Montag, 10. August 2015 schrieb alekiy :

> Assigned #31 <https://github.com/University-of-Potsdam-MM/rooms/issues/31>
> to @DracoBlue <https://github.com/DracoBlue>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/University-of-Potsdam-MM/rooms/issues/31#event-378009769>
> .
>


-- 

  http://dracoblue.net

**Comment by DracoBlue** [comment]
@alekiy 

Also:

http://streifenroller.cs.uni-potsdam.de/rooms/newsProxy.php

sollte eigentlich das rss-feed ausgeben, gibt aber den php-Quelltext aus. Daher gehe ich davon aus, dass dort kein PHP (mod_php) auf dem Server aktiviert ist.
