### ISSUE TITLE
BackBone Refactoring

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/rooms#32]
Hier eine Anfrage, die mir in der Nacht eingefallen ist.
Hast du schon einmal mit [BackBone](http://backbonejs.org/) gearbeitet?
Eine Umstellung hinsichtlich Models und Views würde mir sehr entgegen kommen.
Schätz mal ab wie viel Aufwand das dir bereiten würde.

**Comment by alekiy** [comment]
Erster Entwurf:

#### Models / Collection
- Event / EventCollection
- News / NewsCollection
- Transport / TransportCollection
- FreeRoom / FreeRoomCollection
- Course / CourseCollection (ggf. BookedRoom...)
- Tweet

#### Views
- jeweils eine View für die Elemente von oben
- PageView (Heading, Hauptcontainer, unterer Bereich)

#### Model
- AppModel 
- RSSModel (Feeds)
- ggf. TransportModel seperat oder in Parse von Transport

**Comment by DracoBlue** [comment]
Entwicklungen dazu sind im Branch https://github.com/University-of-Potsdam-MM/rooms/tree/32-backbone-refactor

**Comment by DracoBlue** [comment]
Implementation ist nun:

Model | Collection | View(s)
--------|-----------------|-------
RssItem | EventCollection und NewsCollection extenden BaseRssCollection | EventCollectionView und NewsCollectionView
Transport | TransportCollection | TransportCollectionView und NextTransportView
FreeRoom | FreeRoomCollection | FreeRoomCollectionView
BookedRoom | BookedRoomCollection | NowBookedRoomCollectionView und SoonBookedRoomCollectionView
*-* | *-* | TweetsView

Zusätzlich gibt es noch die `BaseRssCollection` (als Basis für News+EventCollection), sowie die `BaseView` als Basis für alle Views.

Außerdem gibt es ein Singleton unter `config`, welches auch ein Backbone.Model ist. Darin sind nun die Konfigurationen aus der config.json verfügbar und das overriding der Options passiert dort (`&page=2` usw.).

Für das Wechseln zwischen den Seiten gibt es nun den `PageSwitcherView`. Für die Uhrzeit den `CurrentTimeView`.

Was es nicht gibt: Ein `AppModel`, das ist eigentlich das, was das `config`-Singleton macht. `PageView` mit Header und Body, dafür sind leider zu viele `.js_whatever`-Klassen im CSS verwendet worden. Dass müsste man dort komplett auf die nicht geprefixten CSS-Klassen im CSS umbauen und danach kann das im JS refactored werden (z.B. `js_news_headline` wäre generischer als `js_headline`).

**Comment by alekiy** [comment]
Ah das macht einen kleinen Knoten in meinen Kopf aber gut. Hier drei Anmerkungen:

# Struktur

Ich störe mich aktuell nur an der folgenden Struktur:
- models/TransportCollection.js
- collections/transports.js
- views/TransportCollectionView.js

```transport.js``` ist eigtl. keine Collection mehr sondern, gehört so vielmehr in die ```TransportCollectionView.js``` unter initialize und die ```TransportCollection.js``` müsste dann aus dem models-Ordner in den collection-Ordner.

Weißt du wie ich meine?

# Model Config.js

Das Model in der Datei ```js/config.js```kannst du dir auch direkt aus der config.json generieren lassen.

```
var Config = Backbone.Model.extend({
       url: '../../config.json'
    });
```
Dann sind alle Parameter direkt in dem Config-Model.

# Model

Bei den Models hast du auch eine interessante Konstruktion, bspw. in ```models/Transport.js```.

```
var Transport = Backbone.Model.extend({

        getName: function() {
            return this.get('name');
        },

        getCategory: function() {
            return this.get('category');
        },
....
```

Wieso definierst du dir hier nochmal die Funktionen getIdentifier? :)
