### ISSUE TITLE
Dokumentation überarbeiten

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/rooms#37]
- JSDoc
- Readme erweitern
 - Funktionsübersicht
 - neue Konfigurationsmöglichkeiten (z.B. Werbung (HTML))

**Comment by DracoBlue** [comment]
Ich hab die Doku erweitert und die Infos zu MVC von Backbone und der Verwendungslogik in https://github.com/University-of-Potsdam-MM/rooms#mvc-js-objekte hinzugefügt.

Werbung-HTML ist bereits in der README.md enthalten.

@alekiy JSDoc würde ich nicht machen (es muss zusätzlich gehostet und verlinkt sein): mehr bringt es meiner Einschätzung nach, direkt auf den Source der Models zu verlinken und die Kommentare zur Struktur inline zu haben, oder?
