### ISSUE TITLE
Video-Einbindung

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/rooms#39]
Nun noch das letzte Ticket, was als Herausforderung zu verstehen ist.
Einbindung eines Videos auf einer Page-View sofern #38 genutzt wird.

**Comment by DracoBlue** [comment]
In #30

**Comment by alekiy** [comment]
Beispiel-Video
- http://streamup.uni-potsdam.de/flash/83040532_hi.mp4

**Comment by DracoBlue** [comment]
In der Config:

``` json
    "ads_update_frequency": 60,
    "ads": [
      "two.html"
    ]
```

und eine `two.html` mit:

```
The two!

<strong>hai</strong>


<video src="http://streamup.uni-potsdam.de/flash/83040532_hi.mp4" autoplay="autoplay">
</video>
```

Und fertig:

<img width="838" alt="bildschirmfoto 2015-10-29 um 23 17 40" src="https://cloud.githubusercontent.com/assets/35926/10833624/c41d0732-7e93-11e5-9a13-65fc398a217f.png">

**Comment by alekiy** [comment]
Dicht dran, sry. Sollte ähnlich zu den Werbungen sein, d.h. dass in der Config eine Reihe von IDs angegeben werden kann und dann abwechselnd die Videos durchlaufen, wenn die Videos dran sind.
Wenn möglich gleich noch bissel CSS, dass die Videos entsprechend auf dem Screen skalieren.

Ansonsten soweit gute Arbeit. Die Config noch anpassen mit den ads-Paramtern.

**Comment by DracoBlue** [comment]
> Ansonsten soweit gute Arbeit. Die Config noch anpassen mit den ads-Paramtern.

Ist in der README.md dokumentiert. Ich würde das ungern direkt integrieren, wenn in dem integrierten Advertisement nix sinnvolles steht. Hast Du etwas, was ihr drin haben wollt?

> Sollte ähnlich zu den Werbungen sein, d.h. dass in der Config eine Reihe von IDs angegeben werden kann und dann abwechselnd die Videos durchlaufen [...]

Ok. Ich dachte eine der `ads`-Einträge stellt dann einfach ein Video dar? Dadurch seid ihr sehr flexibel (Text unter das Video usw. - das Video wird ziemlich sicher 16:9 und nicht 9:16 sein wodurch oben und unten immer Rand ist). Ich kann gern ein Beispiel machen, wo das Video 100% Platz bekommt. Was meinst Du?

**Comment by alekiy** [comment]
@DracoBlue ahja verstehe. Statt Text und Bild kann ich dann ggf. Video + Text oder nur Video als Active Directory Service-Eintrag verwenden? ;P

Das ist in Ordnung ein Beispiel wie die Konfiguration aussieht kannst du ja auskommentiert in die Config mit aufnehmen. Dann wäre ich glücklich.
Das Video könnten wir dann auch direkt auf den Panels anschauen und entsprechend anpassen.

**Comment by alekiy** [comment]
Noch mit in die Config aufnehmen und dann schließen.

**Comment by DracoBlue** [comment]
Auskommentiert in die "config.json" geht leider nicht, weil JSON keine Kommentare erlaubt und dann die Konfig-Datei invalide wäre :(.

Dokumentiert hab ich es aber in der Beispiel-Konfig der Readme:

https://github.com/University-of-Potsdam-MM/rooms/blame/master/README.md#L51

Hoffe das passt so!

**Comment by alekiy** [comment]
Das ist so passend.
