### ISSUE TITLE
Anführungszeichen sind im RSS-Feed nicht escaped

### ISSUE THREAD

**Issue by DracoBlue** [University-of-Potsdam-MM/rooms#40]
Wenn im Titel ein Anführungszeichen vorkommt, bricht dadurch das RSS-Feed:
``` html
<img src="https://www.uni-potsdam.de/uploads01/tx_upevents/VE_Viva_Warszawa.jpg" width="260"
                        height="100" alt="Buchcover " Viva Warszawa": Peter von Felberg/Steffen Möller" title="
                    Buchcover "Viva Warszawa": Peter von Felberg/Steffen Möller" />
```

Dadurch schlägt leider auch beim Rauminfo-Panel das parsen fehl, wodurch aktuell keine Events angezeigt werden bis "Viva Warszawa" entfernt wird.

@alekiy Das müssen die Leute leider im Typo3 fixen.

**Comment by alekiy** [comment]
@DracoBlue Sollte behoben sein.

**Comment by DracoBlue** [comment]
Klappt aktuell.
