### ISSUE TITLE
Mehrere Werbe-Seiten ermöglichen

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/rooms#43]
Es scheint als ob aktuell nur eine Werbeseite berücksichtigt wird. Sofern eine zweite Seite deklariert wird, scheint diese unbeachtet zu bleiben. @DracoBlue bitte prüfen.

Daher bei einer Verwendung in der index / split.html ggf. die Werbung, die in config.json deklariert ist hintereinander abspielen?
```
<div class="row js_page jsb_ jsb_views/AdView" data-jsb=""></div>
```

**Comment by DracoBlue** [comment]
Im "ads" array der config.json können mehrere Werbungen eingetragen sein.
Bei jeder Iteration wird das nächste aus dem Array genommen.

Zweimal AdsView würde bedeuten man bräuchte zwei Config-Einträge - so war
das zmnd von mir nicht gedacht ;).

Am Sonntag, 17. Januar 2016 schrieb alekiy :

> Assigned #43 <https://github.com/University-of-Potsdam-MM/rooms/issues/43>
> to @DracoBlue <https://github.com/DracoBlue>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/University-of-Potsdam-MM/rooms/issues/43#event-517267341>
> .
>


-- 

  http://dracoblue.net

**Comment by alekiy** [comment]
Passt. Dann war ich zu ungeduldig und habe nicht eine Iteration gewartet. ;D
