### ISSUE TITLE
TransportCollectionView für Split-Screen rechten Bereich

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/rooms#44]
Daher nicht 'NextTransportView' sonder 'TransportCollectionView ' für die rechte Seite.
Per CSS passen wir dann an, dass nur so viele wie sinnvoll erscheinen.
Ich bereite indes eine config.json für Golm vor.

**Comment by DracoBlue** [comment]
Ok, sieht jetzt so aus:

<img width="838" alt="bildschirmfoto 2016-01-17 um 18 41 36" src="https://cloud.githubusercontent.com/assets/35926/12378801/19536ecc-bd4a-11e5-82f5-115ef55f43c9.png">

Da müsste etwas CSS gearbeitet werden ;).
