### ISSUE TITLE
 Videos in Werbung

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/rooms#45]
Wie machen wir es sinnvoll, falls wir Videos in den Werbe-Container einblenden?
Daher die Seiten haben aktuell ja einen festen Durchlaufzeitpunkt, XY Sekunden pro Seite.
Wenn auf einer Werbeseite nun ein Video mit 3 Minuten abgespielt wird, müsste die Seite entsprechend lange auch zu sehn sein und den Aufruf der weiteren Container verzögern...

**Comment by alekiy** [comment]
Sehe gerade du hast eine *ads_update_frequency*: "wie häufig Werbug geladen werden soll"... Der Autor will mir damit was sagen? :)

**Comment by DracoBlue** [comment]
Ich glaube das hilft da leider nicht. Ich schaue mal, ob die Werbung die
weiterblätterzeit irgendwie beeinflussen kann.

Am Sonntag, 17. Januar 2016 schrieb alekiy :

> Sehe gerade du hast eine *ads_update_frequency*: "wie häufig Werbug
> geladen werden soll"... Der Autor will mir damit was sagen? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/University-of-Potsdam-MM/rooms/issues/45#issuecomment-172334371>
> .
>


-- 

  http://dracoblue.net

**Comment by DracoBlue** [comment]
> Sehe gerade du hast eine *ads_update_frequency*: "wie häufig Werbug geladen werden soll"... Der Autor will mir damit was sagen? :)

tut eigentlich was du möchtest. Aber das würde bedeuten, dass die Werbung nur alle 3 Minuten neugeladen wird. Aber nach 10 Sekunden wird trotzdem umgeschalten.

Ich schau mal, dass ich eine Lösung dafür finde.

**Comment by DracoBlue** [comment]
Ist jetzt so möglich:

Wenn die Datei folgenden Tag enthält:

``` html
<meta name="next-page-in" content="260" />
```

wird das Schalten zur nächsten Screen um 260 Sekunden verzögert.

Passt das?

PS: README.md ist auch schon angepasst
PPS: `ads_update_frequency ` wurde entfernt

**Comment by alekiy** [comment]
Ich werde es noch testen, aber es scheint zunächst zu funktionieren.
