### ISSUE TITLE
Aufräumarbeiten

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/rooms#46]
Bitte noch die folgenden Punkte klären:
- [x] Verwendung und Nutzung von Proxys prüfen
- [x] Dokumentation von tests/api-tests.js
- [x] Seiten-Struktur in Readme aktualisieren
Dann sind wir bis auf die letzten Tests durch.

**Comment by DracoBlue** [comment]
Proxys sind bis #22 noch nötig.

**Comment by DracoBlue** [comment]
Doku in der README.md und Quelltext-Kommentare für die Tests und die Funktionsweise eingefügt.

**Comment by DracoBlue** [comment]
Seitenstruktur-Doku massiv erweitert und einige ungenutzte Dateien gelöscht bzw. die übrig gebliebenen in der README.md dokumentiert.
