### ISSUE TITLE
Bestimmte Raumbuchungen highlighten

### ISSUE THREAD

**Issue by DracoBlue** [University-of-Potsdam-MM/rooms#9]

**Comment by alekiy** [comment]
Um es nicht zu kompliziert zu machen genügt es die Liste der Veranstaltungen (nicht Lehrveranstaltungen) durchzugehen und sofern eine oder mehrere Veranstaltungen am gleichen Tag und auf dem jeweiligen Campus sind diese oben mit einer Art Box anzeigen.

**Comment by alekiy** [comment]
- Matching (Raumbuchung und Veranstaltungenstitel) und Klasse hinzufügen
- Aufhängeort des Panels = Standort der Veranstaltung => Kasten bei Veranstaltungen highlighten

**Comment by alekiy** [comment]
kann über Config definiert werden

**Comment by DracoBlue** [comment]
Sowohl auf dem div der Raumbuchungen und dem tr des Events ist jetzt eine `is-highlighted`-Klasse.

Das ist der Fall, wenn ein Event genauso heißt, wie eine Veranstaltung. Bei Events ist das der Fall, wenn der Standort der Veranstaltung dem Parameter `event_location` aus der `config.json` entspricht.

Der Stand ist im 32-backbone-refactor branch.
